name: build_ffmpeg_bunker
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 yasm nasm make wget tar bzip2

      - name: Build in Sandbox
        run: |
          mkdir -p $HOME/ffmpeg_build
          cd $HOME/ffmpeg_build
          wget https://www.ffmpeg.org/releases/ffmpeg-3.4.8.tar.bz2
          tar -xjf ffmpeg-3.4.8.tar.bz2
          cd ffmpeg-3.4.8
          
          # DESACTIVAMOS x86asm Y adts muxer para saltar el error definitivamente
          ./configure \
            --prefix=$HOME/output \
            --enable-static \
            --disable-shared \
            --enable-gpl \
            --arch=x86_64 \
            --target-os=mingw32 \
            --cross-prefix=x86_64-w64-mingw32- \
            --disable-x86asm \
            --disable-muxer=adts \
            --extra-cflags="-fcommon -std=c99"
          
          make -j$(nproc)
          make install

      - name: Upload Finished EXE
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-3.4.8-win64
          path: /home/runner/output/bin/
