name: build_x264_core152
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 yasm nasm make wget tar

      - name: Build x264 Core 152
        run: |
          mkdir -p $HOME/x264_build
          cd $HOME/x264_build
          # Descargamos la versión específica r2854 (Core 152)
          wget https://code.videolan.org/videolan/x264/-/archive/ba24899e/x264-ba24899e.tar.gz
          tar -xzf x264-ba24899e.tar.gz
          cd x264-ba24899e
          
          # Configuración para Windows 64-bit
          ./configure \
            --host=x86_64-w64-mingw32 \
            --cross-prefix=x86_64-w64-mingw32- \
            --enable-static \
            --prefix=$HOME/output
          
          make -j$(nproc)
          make install

      - name: Upload x264 EXE
        uses: actions/upload-artifact@v4
        with:
          name: x264-core152-win64
          path: /home/runner/output/bin/
