name: build_ffmpeg_348_final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 yasm nasm make wget tar bzip2

      - name: Download and Extract
        run: |
          wget https://www.ffmpeg.org/releases/ffmpeg-3.4.8.tar.bz2
          tar -xjf ffmpeg-3.4.8.tar.bz2
          # Entramos a la carpeta y movemos todo afuera para que sea facil de encontrar
          mv ffmpeg-3.4.8/* .

      - name: Configure
        run: |
          ./configure \
            --prefix=./output \
            --enable-static \
            --disable-shared \
            --enable-gpl \
            --arch=x86_64 \
            --target-os=mingw32 \
            --cross-prefix=x86_64-w64-mingw32-

      - name: Compile
        run: make -j$(nproc)

      - name: Install to Output
        run: make install

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-3.4.8-win64
          path: output/bin/
